name: notfiguured
description: itis.team

publish_to: "none"
# major.minor.patch+YYYYMMDDNN (NN - build number. flush every day)
version: 0.3.1+2021071702

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #i18n
  flutter_localizations:
    sdk: flutter
  intl:

  #architecture
  provider: ^5.0.0
  stacked: ^2.2.2

  #database
  get_storage:
    git:
      url: "https://git.itis.team/public-projects/get_storage.git"

  #network
  dio: ^3.0.10
  flutter_offline: ^2.0.0
  chopper: ^3.0.3
  chopper_api:
    path: chopper_api
  # mockito: ^4.1.3

  #firebase and push
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_local_notifications: ^3.0.3
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1

  #auth
  flutter_facebook_auth: ^2.0.2
  flutter_login_vk: ^0.2.0
  flutter_ok_sdk:
    git:
      url: "https://git.itis.team/public-projects/flutter_ok_sdk.git"
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  firebase_auth_oauth: ^0.2.4

  #geo
  geocoder: ^0.2.1
  location: ^3.0.2
  google_maps_flutter: ^1.0.3

  #widgets
  auto_size_text: ^2.1.0
  cached_network_image: ^2.3.3
  flutter_svg: ^0.21.0+1
  flutter_xlider: ^3.3.0
  eva_icons_flutter: ^2.0.1
  pin_code_fields: ^6.0.2
  numberpicker: ^1.3.0
  date_range_picker: ^1.0.6
  percent_indicator: ^2.1.9+1
  syncfusion_flutter_charts: ^19.2.47
  top_snackbar_flutter: ^0.0.3
  flutter_sticky_header: ^0.5.0
  dotted_border: ^2.0.0-nullsafety.0
  native_pdf_renderer: ^3.0.0
  photo_view: ^0.11.1
  flutter_slidable: ^0.6.0

  #features
  supercharged: ^1.10.0
  image_picker: ^0.6.7+12
  extended_masked_text: ^1.1.0
  jiffy: ^3.0.1
  logger: ^0.9.4
  url_launcher: ^5.7.5
  clipboard: ^0.1.2+8
  flutter_form_field_validator: ^1.0.0
  flutter_native_timezone: ^1.0.4
  package_info: ^0.4.3+4
  device_info: ^2.0.0
  flutter_keyboard_visibility: ^4.0.4
  cupertino_icons: ^1.0.2
  get_version: ^0.2.2

dev_dependencies:
  build_runner: ^1.10.7
  json_serializable: ^3.5.1
  pedantic: ^1.9.2
  lint:

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/map/
    - assets/jsons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_intl:
  enabled: true
  main_locale: ru
  class_name: Strings
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
