/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///

part of 'theme.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData succes = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cancel = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData error = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData eye_1 = IconData(0xe809, fontFamily: _kFontFam);
}
