targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/.swagger/'
          output_folder: 'lib/api/'
          include_if_null:
            enabled: true
            value: false
          with_base_url: true